---
- name: Create IAM user and optionally attach policies
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Convert comma-separated string to list (if provided)
      set_fact:
        policy_arns_list: "{{ policy_arns.split(',') if policy_arns | default('') | trim | length > 0 else [] }}"

    - name: Create new IAM user and attach policies if provided
      amazon.aws.iam_user:
        name: "{{ new_iam_username }}"
        state: present
        managed_policy: "{{ policy_arns_list }}"
